import React, { useState, useEffect } from 'react';
import {
  Container,
  Paper,
  Button,
  Select,
  DatePicker,
  Group,
  Stack,
  Text,
  Card,
  Grid,
  Badge,
  Loader,
  Alert,
  Table,
  Tabs,
  SimpleGrid,
  RingProgress,
  ThemeIcon,
} from '@mantine/core';
import { useMantineTheme } from '@mantine/core';
import {
  IconFileText,
  IconDownload,
  IconAlertCircle,
  IconCheck,
  IconCalendar,
  IconClipboardList,
  IconCurrencyDollar,
  IconPackage,
  IconUsers,
  IconShield,
} from '@tabler/icons-react';
import axios from 'axios';
import dayjs from 'dayjs';
import './ReportGenerator.css';
import logger from '../../utils/logger';

/**
 * UC-13: Generate System Reports Component
 * Allows PHC staff to generate comprehensive reports on system operations,
 * financial status, inventory management, patient care, and audit trails
 */
const ReportGenerator = () => {
  const theme = useMantineTheme();
  const [selectedReport, setSelectedReport] = useState('operational');
  const [startDate, setStartDate] = useState(dayjs().subtract(30, 'days').toDate());
  const [endDate, setEndDate] = useState(dayjs().toDate());
  const [loading, setLoading] = useState(false);
  const [reportData, setReportData] = useState(null);
  const [availableReports, setAvailableReports] = useState([]);
  const [error, setError] = useState(null);
  const [successMessage, setSuccessMessage] = useState(null);
  const [activeTab, setActiveTab] = useState('generate');

  // Fetch available report types on component mount
  useEffect(() => {
    fetchAvailableReports();
  }, []);

  const fetchAvailableReports = async () => {
    try {
      const response = await axios.get('/phc/reports/available/', {
        headers: {
          Authorization: `Token ${localStorage.getItem('token')}`,
        },
      });
      
      if (response.data.success) {
        const reports = Array.isArray(response.data.data)
          ? response.data.data.filter((report) => report?.type !== 'ambulance')
          : [];

        setAvailableReports(reports);

        if (!reports.some((report) => report.type === selectedReport)) {
          setSelectedReport(reports[0]?.type || 'operational');
        }
      }
    } catch (err) {
      logger.error('Failed to fetch available reports', err);
      setError('Failed to fetch available reports');
    }
  };

  const handleGenerateReport = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setSuccessMessage(null);

    try {
      const response = await axios.post(`/phc/reports/${selectedReport}/`, 
        {
          start_date: dayjs(startDate).toISOString(),
          end_date: dayjs(endDate).toISOString(),
        },
        {
          headers: {
            Authorization: `Token ${localStorage.getItem('token')}`,
            'Content-Type': 'application/json',
          },
        }
      );

      if (response.data.success) {
        setReportData(response.data.data);
        setSuccessMessage(`${response.data.data.report_type} report generated successfully!`);
        setActiveTab('view');
      } else {
        setError(response.data.message || 'Failed to generate report');
      }
    } catch (err) {
      logger.error('Failed to generate report', err);
      setError(err.response?.data?.message || 'Error generating report. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadCSV = () => {
    if (!reportData) return;

    const metrics = reportData.metrics;
    const csv = [
      ['Report Type', reportData.report_type],
      ['Generated At', reportData.generated_at],
      ['Generated By', reportData.generated_by],
      [''],
      ['Period'],
      ['Start Date', reportData.period.start_date],
      ['End Date', reportData.period.end_date],
      [''],
      ['Metrics'],
      ...Object.entries(metrics).map(([key, value]) => [
        key.replace(/_/g, ' ').toUpperCase(),
        typeof value === 'object' ? JSON.stringify(value) : value,
      ]),
    ]
      .map(row => row.join(','))
      .join('\n');

    const element = document.createElement('a');
    element.setAttribute('href', `data:text/csv;charset=utf-8,${encodeURIComponent(csv)}`);
    element.setAttribute('download', `${reportData.report_type}_report_${dayjs().format('YYYY-MM-DD')}.csv`);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const getReportIcon = (type) => {
    const icons = {
      operational: <IconClipboardList size={20} />,
      financial: <IconCurrencyDollar size={20} />,
      inventory: <IconPackage size={20} />,
      patient_care: <IconUsers size={20} />,
      audit: <IconShield size={20} />,
    };
    return icons[type] || <IconFileText size={20} />;
  };

  const renderMetricsGrid = (metrics) => {
    const metricEntries = Object.entries(metrics).filter(([_, value]) => typeof value !== 'object');

    return (
      <SimpleGrid cols={2} spacing="lg" breakpoints={[{ maxWidth: 'sm', cols: 1 }]}>
        {metricEntries.map(([key, value]) => (
          <Paper key={key} p="md" radius="md" withBorder>
            <Group position="apart">
              <div>
                <Text size="sm" color="dimmed" weight={500}>
                  {key.replace(/_/g, ' ').replace(/_/g, ' ').toUpperCase()}
                </Text>
                <Text size="lg" weight={700} mt={5}>
                  {typeof value === 'number' ? value.toLocaleString() : value}
                </Text>
              </div>
              <ThemeIcon size="lg" variant="light" radius="md">
                {getReportIcon(selectedReport)}
              </ThemeIcon>
            </Group>
          </Paper>
        ))}
      </SimpleGrid>
    );
  };

  const renderActionBreakdown = (breakdown) => {
    if (!breakdown) return null;

    const rows = Object.entries(breakdown).map(([action, count]) => (
      <tr key={action}>
        <td>{action.replace(/_/g, ' ').toUpperCase()}</td>
        <td align="right">{count}</td>
      </tr>
    ));

    return (
      <Paper p="md" radius="md" withBorder>
        <Text weight={700} mb="md">
          Action Breakdown
        </Text>
        <Table striped highlightOnHover>
          <thead>
            <tr>
              <th>Action</th>
              <th align="right">Count</th>
            </tr>
          </thead>
          <tbody>{rows}</tbody>
        </Table>
      </Paper>
    );
  };

  return (
    <Container size="lg" py="xl" className="report-generator">
      <Stack spacing="lg">
        {/* Header */}
        <div>
          <Group position="apart" align="center" mb="md">
            <div>
              <Text size="xl" weight={700} className="header-title">
                System Reports
              </Text>
              <Text size="sm" color="dimmed">
                Generate comprehensive operational, financial, inventory, patient care, and audit reports
              </Text>
            </div>
            <Badge size="lg" variant="filled" leftSection={<IconFileText size={14} />}>
              UC-13
            </Badge>
          </Group>
        </div>

        {/* Alerts */}
        {error && (
          <Alert icon={<IconAlertCircle size={16} />} title="Error" color="red">
            {error}
          </Alert>
        )}
        {successMessage && (
          <Alert icon={<IconCheck size={16} />} title="Success" color="green">
            {successMessage}
          </Alert>
        )}

        <Tabs value={activeTab} onTabChange={setActiveTab}>
          <Tabs.List>
            <Tabs.Tab value="generate" icon={<IconFileText size={14} />}>
              Generate Report
            </Tabs.Tab>
            <Tabs.Tab value="view" icon={<IconClipboardList size={14} />} disabled={!reportData}>
              View Report
            </Tabs.Tab>
          </Tabs.List>

          <Tabs.Panel value="generate" pt="xl">
            <Paper p="lg" radius="md" withBorder className="report-form">
              <Stack spacing="md">
                {/* Report Type Selection */}
                <div>
                  <Text weight={600} mb="sm">
                    Select Report Type
                  </Text>
                  <Grid gutter="md">
                    {availableReports.map((report) => (
                      <Grid.Col key={report.type} span={{ base: 12, sm: 6 }} md={4}>
                        <Paper
                          p="md"
                          radius="md"
                          withBorder
                          onClick={() => setSelectedReport(report.type)}
                          className={`report-card ${selectedReport === report.type ? 'active' : ''}`}
                          style={{
                            cursor: 'pointer',
                            borderColor: selectedReport === report.type ? theme.colors.blue[6] : undefined,
                            backgroundColor:
                              selectedReport === report.type ? theme.colors.blue[0] : undefined,
                          }}
                        >
                          <Group position="apart" mb="xs">
                            <ThemeIcon size="lg" variant="light" radius="md">
                              {getReportIcon(report.type)}
                            </ThemeIcon>
                            {selectedReport === report.type && (
                              <Badge size="sm" color="blue">
                                Selected
                              </Badge>
                            )}
                          </Group>
                          <Text weight={600} size="sm">
                            {report.name}
                          </Text>
                          <Text size="xs" color="dimmed" mt={5}>
                            {report.description}
                          </Text>
                        </Paper>
                      </Grid.Col>
                    ))}
                  </Grid>
                </div>

                {/* Date Range Selection */}
                <Stack spacing="sm">
                  <Text weight={600}>
                    Select Date Range
                  </Text>
                  <Group grow>
                    <DatePicker
                      label="Start Date"
                      placeholder="Pick start date"
                      value={startDate}
                      onChange={setStartDate}
                      maxDate={endDate}
                      icon={<IconCalendar size={16} />}
                    />
                    <DatePicker
                      label="End Date"
                      placeholder="Pick end date"
                      value={endDate}
                      onChange={setEndDate}
                      minDate={startDate}
                      icon={<IconCalendar size={16} />}
                    />
                  </Group>
                </Stack>

                {/* Quick Date Range Buttons */}
                <Group spacing="xs">
                  <Text size="sm" color="dimmed" weight={500}>
                    Quick Range:
                  </Text>
                  <Button
                    size="xs"
                    variant="light"
                    onClick={() => {
                      setStartDate(dayjs().subtract(7, 'days').toDate());
                      setEndDate(dayjs().toDate());
                    }}
                  >
                    Last 7 Days
                  </Button>
                  <Button
                    size="xs"
                    variant="light"
                    onClick={() => {
                      setStartDate(dayjs().subtract(30, 'days').toDate());
                      setEndDate(dayjs().toDate());
                    }}
                  >
                    Last 30 Days
                  </Button>
                  <Button
                    size="xs"
                    variant="light"
                    onClick={() => {
                      setStartDate(dayjs().subtract(90, 'days').toDate());
                      setEndDate(dayjs().toDate());
                    }}
                  >
                    Last 90 Days
                  </Button>
                </Group>

                {/* Generate Button */}
                <Button
                  fullWidth
                  size="md"
                  onClick={handleGenerateReport}
                  loading={loading}
                  leftIcon={<IconFileText size={18} />}
                >
                  {loading ? 'Generating Report...' : 'Generate Report'}
                </Button>
              </Stack>
            </Paper>
          </Tabs.Panel>

          <Tabs.Panel value="view" pt="xl">
            {reportData && (
              <Stack spacing="lg">
                {/* Report Header Info */}
                <Paper p="lg" radius="md" withBorder className="report-info">
                  <Grid gutter="lg">
                    <Grid.Col span={{ base: 12, sm: 6 }}>
                      <div>
                        <Text size="sm" color="dimmed" weight={500}>
                          Report Type
                        </Text>
                        <Group>
                          <ThemeIcon size="lg" variant="light" radius="md">
                            {getReportIcon(reportData.report_type)}
                          </ThemeIcon>
                          <div>
                            <Text weight={600}>{reportData.report_type.replace(/_/g, ' ').toUpperCase()}</Text>
                            <Text size="sm" color="dimmed">
                              Generated by {reportData.generated_by}
                            </Text>
                          </div>
                        </Group>
                      </div>
                    </Grid.Col>
                    <Grid.Col span={{ base: 12, sm: 6 }}>
                      <div>
                        <Text size="sm" color="dimmed" weight={500}>
                          Report Period
                        </Text>
                        <Text weight={600}>
                          {dayjs(reportData.period.start_date).format('MMM DD, YYYY')} -{' '}
                          {dayjs(reportData.period.end_date).format('MMM DD, YYYY')}
                        </Text>
                        <Text size="sm" color="dimmed">
                          Generated {dayjs(reportData.generated_at).fromNow()}
                        </Text>
                      </div>
                    </Grid.Col>
                  </Grid>
                </Paper>

                {/* Metrics Display */}
                <div>
                  <Text weight={700} size="lg" mb="md">
                    Report Metrics
                  </Text>
                  {renderMetricsGrid(reportData.metrics)}
                </div>

                {/* Action Breakdown for Audit Reports */}
                {reportData.report_type === 'audit' && reportData.metrics.action_breakdown && (
                  renderActionBreakdown(reportData.metrics.action_breakdown)
                )}

                {/* Download Button */}
                <Group>
                  <Button
                    leftIcon={<IconDownload size={18} />}
                    onClick={handleDownloadCSV}
                  >
                    Download as CSV
                  </Button>
                </Group>
              </Stack>
            )}
          </Tabs.Panel>
        </Tabs>
      </Stack>
    </Container>
  );
};

export default ReportGenerator;
